### ISSUE TITLE
Erschliessung

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#10]
Diese Angabe fehlt.

Vollerschlossen
Teilerschlossen
Unerschlossen

**Comment by jaggli** [comment]
Probably related to #65 ?

**Comment by jaggli** [comment]
We already have
- hasSupplyPower
- hasSupplySewage
- hasSupplyWater
- hasSupplyGas

Should we add `hasSupplyRoad` instead, because then we can interpret the development and do not have to specify it redundantly. @jensstalder

**Comment by jensstalder** [comment]
Sadly thats what we tried before, it is however more involved than this. At the end of the day the development level is something defined very relatively, where they can, for example, differ based on category etc. As fahr as i know these 3 levels are communicated as is in swiss housing contracts. as full partial and undeveloped without having a direct relation to the has* you've specified. They "tend" to be based on them, but are not "certain". Thats why it's easier to define these separately.

**Comment by jaggli** [comment]
Thanks for clarification. So we will
- add a simple type `property > development` with an enum
  - full
  - partial
  - undeveloped
