### ISSUE TITLE
docs page should keep xsd fields order ( in translation)

### ISSUE THREAD

**Issue by elvisbegovic** [qualipool/swissrets#112]
## Main topic

- Technical understanding

## Precise and short description of your question
Considering this pages https://github.com/qualipool/swissrets/blob/master/docs/Categories.md 

Can we respect xsd order to descript fields in your docs pages, if I take one example to demonstrate consider this page  https://github.com/qualipool/swissrets/blob/master/docs/Categories.md

in first table you have this order
![image](https://user-images.githubusercontent.com/2789203/66049097-10387280-e52b-11e9-90c5-044b5ea5d142.png)

while in second table (translations) you have this order:
![image](https://user-images.githubusercontent.com/2789203/66049154-28a88d00-e52b-11e9-8327-6f73c0f30f2a.png)

this is not human/tools readable/parseable, what you think ?

**Comment by jensstalder** [comment]
We agree. Can you create a PR for this? Thanks. @elvisbegovic
