### ISSUE TITLE
Possibility to send flag for video-tour/call availability

### ISSUE THREAD

**Issue by rgutzwiller** [qualipool/swissrets#121]
**Problem description**
Given the current situation caused by the COVID-19 pandemic, video calls or guided virtual tours are a viable option to still do property visits where physical contact is not possible anymore / not recommended. While major real estate platforms are integrating visual flags to support prospects and real estate agencies, this is not supported in the transaction standard so far.

**Desired Solution**
A standardised way to indicate that prospects can visit the property virtually (i.e. with a video-call or guided virtual-tour hosted by the real estate agent). This would be beneficial for both real estate software providers and the real estate platforms in order to offer this feature well beyond the current situation.

**Comment by jensstalder** [comment]
Possible characteristics?
```
<characteristics>
   <hasLiveVirtualTours>applies</hasLiveVirtualTours>
   <hasLiveVideoTours>applies</hasLiveVideoTours>
   <hasStreamedTours>applies</hasStreamedTours>
</characteristics>
```

**Comment by josias-r** [comment]
Are flags necessary that "digital files exist" anyways? I can understand why there should be a <hasLiveVideoTour> flag since this would be something unknown to the digital system without a flag.
But the other two seem redundant since in the system you could just check whether there are corresponding files exist or not?

Instead of flags, why not information to the data source itself... links / the contact information? Because that would still be useful with just the XML itself? 🤷🏻‍♂️

**Comment by jensstalder** [comment]
There is not going to be a "file" or "link" atm. Just a flag/feature that it is offered by the real-estate agent as an information.

**Comment by josias-r** [comment]
Oh, I see now from some examples. Yeah, in that case, your proposal seems fine.

**Comment by jensstalder** [comment]
Yes, but which one ^^

**Comment by jensstalder** [comment]
I think it needs to have something like "live" or "call" so that it is not confused with a asynchronous virtual tour right?

**Comment by jensstalder** [comment]
homegate uses the term `virtual visitaion` or `remote viewings` or similar. so maibe
```xml
<hasVirtualVisitation>applies<hasVirtualVisitation>
<hasRemoteViewings>applies<hasRemoteViewings>
```

**Comment by jaggli** [comment]
The straight forward `hasRemoteViewings` sounds good to me.

**Comment by jensstalder** [comment]
That has my vote aswell then :-)
We will implement that wording pre-maturely with the IDX conversion for now. I guess we will need to implement that before we switch to sending SwissRETS in the future to avoid loosing this feature ;-) . Just wanted to get the wording right so should be fine for now. thanks.

**Comment by jensstalder** [comment]
Possible future implemntation we will need to create a breaking change and implement a more complex component.

```
<virtualVisitation>

<virtualVisitation>
```
