### ISSUE TITLE
Additional heating generation options

### ISSUE THREAD

**Issue by rgutzwiller** [qualipool/swissrets#127]
**Problem description**
Currently available in for heating generation:
https://swissrets.ch/docs/noNamespace/element/export.properties.property.heating.generation.html

Additional options:
- Wärmepumpe Sole-Wasser (brine water heatpump) 
- Elektro (electric)
- Alternativ (alternative)
- Blockheizkraftwerk (?)
- Ergänzendes dezentrales Warmwasser (?)
- Kohle (coal)
- Flüssiggas (liquified gas)
- Holz & Hackschnitzel (wood chips)

**Desired Solution**
Add the options mentioned above

**Comment by jensstalder** [comment]
@rgutzwiller 
These are the currently available heat generation types:

**district:** A system for distributing heat generated in a centralized location through a system of insulated pipes into a network.
**electricity:** electricity - Electrical energy is converted to heat energy for space heating.
**gas:** gas - Heating by burning natural gas, liquefied petroleum gas, propane or butane.
**geothermal-probe:** geothermal-probe -
**heatpump-air-and-water:** heatpump-air-and-water -
**heatpump:** heatpump - Heating and/or cooling system that transfers heat to or from the ground using a pump.
**oil:** oil - Heating by burning fosile heating oil.
**photovoltaics:** photovoltaics - In general, thermal photovoltaics use solar cells to convert the light that radiates from a hot surface into electricity and/or heating water.
**solar-thermal:** solar-thermal - The conversion of sunlight into heat for water heating using a solar thermal collector
**wood-pellet:** wood-pellet - Wood pellets, small pellets from wood chips and sawdust, are combusted.
**wood:** wood - Burning wood fuel and wood-derived biomass fuel, such as sawdust bricks.

Can you distinguish which are not covered already? Then we can add them appropriately.

**Comment by rgutzwiller** [comment]
I think this is the diff:

Wärmepumpe Sole-Wasser (brine water heatpump)
Alternativ (alternative)
Blockheizkraftwerk (?)
Ergänzendes dezentrales Warmwasser (?)
Kohle (coal)

**Comment by jensstalder** [comment]
**Wärmepumpe Sole-Wasser (brine water heatpump)** sound similar to heatpum-air-and-water need to research if this warrants a differentiation.

**Alternativ (alternative):** This seams like a noop to me and should not be explicitly stated. Aka. there is some heating by default usually right? Having a "anything else" option is usually problematic down the road.

**Blockheizkraftwerk (?)** can't fin a translation maibe we can just add the abbreviation instead? `bhkw` sounds like a very exclusively german thing to me.

**Ergänzendes dezentrales Warmwasser (?)** sounds similar to heatpump need to research if this warrants a differentiation.

**Kohle (coal)** sure seams like something we can add ^^ "coal"

**Comment by jensstalder** [comment]
The only sure thing is coal. :-) Adjust PR to only do this for the moment. We created a project to fix/clean up this topic in a breaking release in the future.

**Comment by jensstalder** [comment]
These are the leftover heating types that are still open for discusion. In case reintroduction is necesarry some time in the future:

```xml
<xs:enumeration value="heatpump-brine-and-water">
    <xs:annotation>
    <xs:documentation>heatpump-brine-and-water - Heat is generated using earthern temperature and transported with water to the surface.</xs:documentation>
    </xs:annotation>
</xs:enumeration>
<xs:enumeration value="bhkw">
    <xs:annotation>
    <xs:documentation>bhkw - A block-type thermal power station (BHKW) is a modular system for generating electrical energy and heat, which is preferably operated at the place where the heat is consumed.
        .</xs:documentation>
    </xs:annotation>
</xs:enumeration>
```
