### ISSUE TITLE
New characteristic "lärmminimiert/homeoffice-tauglich" 

### ISSUE THREAD

**Issue by rgutzwiller** [qualipool/swissrets#136]
**Problem description**
Real estate platforms and software providers were approached by [http://igrw.ch/](http://igrw.ch/) to add a new property characteristic. 

**Desired Solution**
New characteristic "lärmminimiert/homeoffice-tauglich" 

**Original message**
Grüezi mitenand

Ich leite das Projekt "ruhiges und rücksichtsvolles Wohnen"   www.igrw.ch  

Auch als E-Buch erschienen bei Amazon:  "ruhiges und rücksichtsvolles Wohnen und Arbeiten in Zeiten der Verdichtung".

Wir sind bereits über 50 Interessenten aus der ganzen Schweiz, die sich sehnlichst ruhigen Wohnraum wünschen, und es werden wöchentlich mehr. Nicht erst während der Coronakrise zeigte sich, dass die meisten bestehenden Immobilien für Home Office kaum geeignet sind, weder für Eltern mit Kindern noch für Menschen ohne Kinder, die den Lärm der Nachbarn ertragen müssen. Da die Immobilienbranche sich bislang nach unserer Erfahrung für das Bedürfnis nach ruhigem Wohnen und Arbeiten nicht interessiert hat, muss sie nun technisch gezwungen werden, sich damit auseinanderzusetzen. Der Grund: Die Verdichtung ist nicht aufzuhalten und die Arbeitswelt verändert sich rasant. Das Konfliktpotential in den Häusern steigt. Sowohl Toleranz als auch Rücksichtnahme haben ihre Grenzen. Welcher Vermieter will schon dauernd schlichten müssen?

Im Namen aller Ruhesuchenden bitte ich Sie deshalb, auf Ihren Immobilienportalen das harte Suckriterium "ruhig/lärmminimiert/homeoffice-optimiert" (oder ähnlich) einzuführen. Gernrn helfen wir Ihnen dabei. 

Definition von ruhig/lärmminimiert/homeoffice-tauglich: "gut nach innen und aussen lärmisolierter Wohnraum, wo man kein Trampeln, Geklopfe, Geschepper, Getöse, Geschrei etc. hört. Rücksichtsvolle Nachbarschaft, die keinen unnötigen Lärm verursacht." (Grundlage wäre eine Hausordnung, die jeder Mieter unterschreiben muss, und bei offensichtlicher Nichteinhaltung kann das Mietverhältnis gekündigt werden).

-> Achtung: "ruhig" ist nicht gleich "familienfreundlich". Kleinkinder sind schwer kontrollierbar und sollen auch mal toben und schreien dürfen. Daher wäre das Kriterium wohl besser "lärmminimiert/homeoffice-tauglich".

Das Ziel ist das Trennen der Anspruchsgruppen "ruhig" von "lebhaft/laut": Das macht das Erstellen von ruhigen Wohnraums in rücksichtsvoller Nachbarschaft für lärmsensible Menschen (ca. 20% der Bevölkerung) notwendig oder Umnutzung bestehenden Wohnraums. -> "ruhig lebt mit ruhig". Home Office und entspanntes Wohnen wird somit möglich.

Bei den herkömmlichen Siedlungen ("lebhaft lebt mit lebhaft") müsste das Home Office in einem ruhigerem Nebentrakt liegen. Aber das ist nicht die Sache der Immobilienportale, sondern der Architekten und Bauherren.

Sie finden anbei unseren offenen Brief an die Immobilienbesitzer, den Sie gern an Immobilienmakler oder Immobilienbesitzer weiterleiten dürfen.

Vielen Dank für Ihre Hilfe im Namen aller (verzweifelten) Ruhesuchenden!

**Comment by jensstalder** [comment]
Looks very subjective. And the portals could probably solve this better.
