### ISSUE TITLE
extra cost propertysegment needs to be defined

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#14]
<netPrice timesegment="y" propertysegment="m2">1250</netPrice>
            <grossPrice timesegment="y" propertysegment="m2">1600</grossPrice>
            <extraCosts>
                <extraCost timesegment="y" **propertysegment="m"** title="Nebenkosten" type="">250</extraCost>
            </extraCosts>

Needs to be handled identically to the global price definition.

**Comment by jaggli** [comment]
solved in #53
