### ISSUE TITLE
Field additions on project & unit levels to export entire development projects (projects/units/properties)

### ISSUE THREAD

**Issue by rgutzwiller** [qualipool/swissrets#142]
**Problem description**
So far, there's a minimal number of fields available in SwissRETS for the export of entire development projects (consisting of multiple units / multiple properties per unit). 

See: 
https://swissrets.ch/docs/noNamespace/element/export.projects.html
https://github.com/qualipool/swissrets/blob/master/examples/full.xml

**Desired Solution**
Additional fields to export basic informations about the development project / units in order for publishers (real estate classifieds/marketplaces and/or individual webpages) to display the information properly. 

For an MVP version we suggest the following additions: 

Project level: 
- Project name
- Project short description
- Project location
- Project logo
- Construction status
- Total number of residential units
- Available from
- Price from
- Price to
- M2 Livingspace from
- M2 Livingspace to
- Number of rooms from
- Number of rooms to
- Project photos
- Dedicated project website link
- Project videos link (youtube, or others)
- Developer description
- Developer logo
- Developer image

Unit level: 
- Unit name
- Total number of floors

**Comment by jensstalder** [comment]
The following fields stand in contest:

- Total number of residential units
- Price from
- Price to
- M2 Livingspace from
- M2 Livingspace to
- Number of rooms from
- Number of rooms to

We need to find out if we could live without these fields for now.

They might be re-defining existing values calculable based on available offers.

To consider:
- Pre-Projects: Projects that are announced before actual offers are present.

**Comment by jensstalder** [comment]
Should probably add the following fields
* usable space from (Nutzfläche von)
* usable space to  (Nutzfläche bis)

One should only fill these fields if it contains applicable offers.

**Comment by jensstalder** [comment]
These are the possible offers and their possible pricing definitions:
`<rent><gross>`
`<rent><net>`
`<buy><price>`

We should probably make it possible to define these ranges separately then? Example:

```xml
<rent>
   <netFrom>
   <netTo>
</rent>
<buy>
   <priceFrom>
   <priceTo>
</buy>
```

Also should we include propertySegment (m2) and timeSegment (/Month/Year) values as well?

**Comment by jensstalder** [comment]
"commercial" would also need to be added for completeness.

```
<numberOfResidentialUnits>
<numberOfCommercialUnits>
```

**Comment by jensstalder** [comment]
Current proposal WIP

```
<export>
  <projects>
    <project id="unique within xml and should be consistent">
       <referenceId>{nice reference string}</referenceId>
       <units>
         <unit id="unique within xml and should be consistent">
           <referenceId>{nice reference string}</referenceId>
           <properties>
             <propertyRef>{ID of property within <properties>}</propertyRef>
```

Additions
```
<export>
  <projects>
    <project>
        Project name
        Project short description
        Project location
        Project logo
        Construction status
        Total number of residential units
        <numberOfResidentialUnits/>
        <numberOfCommercialUnits/>
        Available from
        <prices>
            <rent>
               <netFrom/>
               <netTo/>
            </rent>
            <buy>
               <priceFrom/>
               <priceTo/>
            </buy>
        </prices>
        <areaSiaNfFrom/>
        <areaSiaNfTo/>
        <areaBwfFrom/>
        <areaBwfTo/>
        <usableSpaceFrom/>
        <usableSpaceTo/>
        Number of rooms from
        Number of rooms to
        Project photos
        Dedicated project website link
        Project videos link (youtube, or others)
        Developer description
        Developer logo
        Developer image
       <units>
         <unit>
           <properties>
             <propertyRef></propertyRef>
```

**Comment by jensstalder** [comment]
Small concern that I just realised.

The current structure allows for properties to be connected to multiple projects/units (manyToMany) This might actually make things a bit complicated. We should think about putting the reference to a unit within the property itself instead and remove the "properties" section here. That way a property can only belong to one unit and this would make things a little more restrictive and simpler. Unless there is a use case for a property to exist within multiple projects/units?

But I guess this would require an alteration of the existing schema and would be a different issue. I can create one if that is a concern that is shared, and not just my paranoia speaking :-) .

**Comment by jensstalder** [comment]
Special stream will happen:

Casasoft will organise this.

**Comment by MTrachsel** [comment]
Immoscout24 would be very interested in having this feature within the Standard and we believe this could be very usefull to Immo Developer and the adoption of the standard.

**Comment by MTrachsel** [comment]
Based on our discussion yesterday we can exlude the developer infos for now and proceed with the discussion on the construction status. The Developer infos may be of interest in a later version.

**Comment by jensstalder** [comment]
We had a short meeting with the involved folks. We are ready to create a PR leaning heavily on the proposal above. Excluding developers for now, and using simple constructionStatus options to start with. These two could be added later on down the road once they become relevant.
