### ISSUE TITLE
missing detail changelog (feature, fix)

### ISSUE THREAD

**Issue by elvisbegovic** [qualipool/swissrets#150]
## Main topic

- Missing documentation

## Precise and short description of your question
Hi, we implemented swissrets 30 oct. 2019.
However, seeing Issues it seems development continues. Is here a changelog of what change since 1year. 
(This https://github.com/qualipool/swissrets/releases isn't up to date cause no release/enough for us.)

Thank you
TSAB Thurnherr SA

**Comment by jensstalder** [comment]
There have actually not been releases beyond version 2.0. We already have a meeting setup to manage future releases and there will be changes in the near future. We will add to the release notes as soon as there are new releases. We did not want to add changes as it is still in early adoption. If you are interested in what will be added take a look at the individual PRs. These usually have the documentation changes baked in. Hope that helps. Please reopen this issue with further questions if something was not clear.

**Comment by jensstalder** [comment]
I also added the PRs and issues that will probably be addressed in the 2.1 version https://github.com/qualipool/swissrets/milestone/3 if you are curious.
