### ISSUE TITLE
Interessenten Kontaktmeldungen

### ISSUE THREAD

**Issue by andibraunhangartner** [qualipool/swissrets#16]
Es wäre wünschenswert, wenn der swissRETS Standard nebst dem Anwendungsfall Objekte publizieren ebenso auch Anwendungsfälle rund um den "Interessenten Kontakt" abdecken würde.

Dies wären aus meiner Sicht:

- Frage/Meldung via Kontaktformular
- Anmeldung Besichtigungstermin
- Bewerbungsformular Miete

Besten Dank fürs Berücksichtigen.
Ich stehe gerne für Rückfragen zur Verfügung.

**Comment by jaggli** [comment]
Need more clarification on this.

**Comment by jaggli** [comment]
@andibraunhangartner without further clarification, I'll close the issue by the end of January.

**Comment by andibraunhangartner** [comment]
There are three different use cases mentioned in the issue:

1. Frage/Meldung via Kontaktformular
An interested person contacts the agency with questions about the real estate/unit. swissRETS should define a standard dataset for such a contact. at the moment all the contact takes place over email or phone. There is no contact history like e.g. a chat. if an agency publishes a real estate/unit on several portals, they have to gather all the different contacts from interested people manually. With an standardised API there would be a possibility to collect and manage all the contacts in just one application.

2. Anmeldung Besichtigungstermin
As well as the contact (see 1.) with an interested person, there should be a feedback dataset if a  viewing date is booked or unbooked.

3. Bewerbungsformular Miete
If the portal provides a registration form for interested people (e.g. like flatfox is doing) this data could be transfered/downloaded directly to the ERP where the original ad was coming from.

If you need more information about this issue, please let me know.

**Comment by andibraunhangartner** [comment]
Maybe all this use cases are topic for https://github.com/qualipool/swissrets-feedback. Since there is not really a description what it stands for, i'm not shure if its the right place...
Should I transfer the issues to swissrets-feedback?

**Comment by jaggli** [comment]
Yes please copy it over to feedback, that's exactly what this is for @andibraunhangartner thank you
