### ISSUE TITLE
Abrechnung Inseratekosten

### ISSUE THREAD

**Issue by andibraunhangartner** [qualipool/swissrets#17]
Es wäre wünschenswert, wenn der swissRETS Standard ebenfalls Definitionen zur Abrechnung der Inseratekosten enthält. Hierbei ist nicht die Rechnungsstellung gemeint, sondern eine detaillierte Aufstellung, welche Objekte, wie viele effektive Kosten verursacht haben bzw. ebenso weitere Statistische Daten zum Objekt wie:

- Kosten
- Dauer Online
- Anzahl Klicks
- Dauer TopListing
- Anzahl Kontaktanfragen
- usw.

Besten Dank für die Berücksichtigung.
Bei Fragen stehe ich gerne zur Verfügung.

**Comment by jaggli** [comment]
I don't think we should have this in the transaction standard, this is what we are trying to do over here https://github.com/qualipool/swissrets-feedback
