### ISSUE TITLE
Document: Inquiry Person data should be kept secret

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#186]
The original intent was to differentiate `contactPerson` with `inquiryPerson` so that contactPerson can be previewed/presented within the listing as a contact person. And `inquiryPerson` should only be used to send emails (or sms) to.

Current Documentation is a bit wischi-waschi:
```
person	contactPerson
          Contact person for questions and typically responsible for making appointments.
person	inquiryPerson
          Person responsible for receiving inquiries and applications.
organization	organization
          The company selling
person	visitPerson
          Person responsible opening the door for visiting.
```

**Comment by jensstalder** [comment]
We should clearly state that the `inquiryPerson` contact credentials should not be shared publicly, to avoid spam and the like.

**Comment by jensstalder** [comment]
We should also add that parsable emails such as "remcat" need to be placed within inquiryPerson.

**Comment by jensstalder** [comment]
**Also a thought:** If it realy is required to indicate what type of inquiry is expected then we should add that within the inquiryPerson istead. Just some random ideas:

```xml
<inquiryPerson>
    <email>some@email.com</email>
    <accept>document/remcat</accept> <!-- inspired by http header "Accept" value https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.2 -->
    <contentType></contentType> <!-- https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5 -->
</inquiryPerson>
```

**Comment by merrycoder** [comment]
> Current Documentation is a bit wischi-waschi

Agree, the roles of `contactPerson` and `inquiryPerson` are not sufficiently determined at the moment, especially concerning which contact should received email notifications.
