### ISSUE TITLE
parcelNumbers: implicit collection

### ISSUE THREAD

**Issue by ThomasBietenhader** [qualipool/swissrets#19]
The plural in the element `<parcelNumbers>`'s name suggests a collection of numbers which is not reflected by its type of `xs:string`.

If the element represents a collection of values the structure should be changed accordingly.

**Comment by jaggli** [comment]
@ThomasBietenhader what is the parcelNumbers field used for? I would like to add documentation and being able to take a decision for this.

**Comment by ThomasBietenhader** [comment]
@jaggli I guess parcelNumbers refers to "Parzellennummer". We actually don't support "Parzellennummer" anymore in our internal data model. I just noted the inconsistency between name and structure (or lack thereof).

**Comment by jaggli** [comment]
Added documentation
