### ISSUE TITLE
availability: meaning of value private

### ISSUE THREAD

**Issue by ThomasBietenhader** [qualipool/swissrets#20]
Provide explanations for the values for element `<availability>`. E.g. the meaning of `private` is not evident.

**Comment by jaggli** [comment]
Yes there is missing documentation. @jensstalder do you know what private means, currently we have this for 'availability'

```
                          <xs:enumeration value="reserved" />
                          <xs:enumeration value="active" />
                          <xs:enumeration value="taken" />
                          <xs:enumeration value="reference" />
                          <xs:enumeration value="private" />
```

**Comment by jensstalder** [comment]
Some customers want a "private" section on their website that show "exclusive" properties that usually need some sort of login. Thats what the "private" availability is used for. aka. it's only privately available.

**Comment by jaggli** [comment]
Thank you. Will add this to the documentation. @jensstalder

**Comment by jaggli** [comment]
Ah sorry, Zoe explained it to me. These are broker reference objects. All good.

**Comment by jaggli** [comment]
completed documentation in `feature/refactoring`
