### ISSUE TITLE
Cos-nonambig validation issue

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#204]
**Describe the bug**
Some parsers are detecting a Cos-nonambig issue on the latest 2.4 schema. This could (depending on implementations) cause systems to opt-out, and not parse the XML.

```
Cos-nonambig: Gross And Gross (or Elements From Their Substitution Group) Violate "Unique Particle Attribution". During Validation Against This Schema, Ambiguity Would Be Created For Those Two Particles.
```

Current discussion is on slack: https://qualipool.slack.com/archives/CB28KC4TW/p1636037112000800

**Comment by jensstalder** [comment]
Tasks

- [ ] Find a way to avoid the error, (consider minOccurs="0") 
- [ ] Add (at least) a .net validator as well for cross-validator-comparisions. more is better 😉

**Comment by jensstalder** [comment]
Since we are also adding it I guess it would not be inconsistent to also add

- [ ] Add a validator for PHP

Since casasoft uses a bit of PHP we could implement that.

There are other major languages as well though: for Example

- [ ] Java
- [ ] Your favorite language here

They would need to be made from folks that actually know how to implement them. I guess they will become relevant by usage/implementers of the standard.

**Comment by merrycoder** [comment]
> Since we are also adding it I guess it would not be inconsistent to also add
> 
> * [ ]  Add a validator for PHP
> 
> Since casasoft uses a bit of PHP we could implement that.
> 
> There are other major languages as well though: for Example
> 
> * [ ]  Java
> * [ ]  Your favorite language here
> 
> They would need to be made from folks that actually know how to implement them. I guess they will become relevant by usage/implementers of the standard.

* [ ]  .NET Core
