### ISSUE TITLE
property/start: name does not reveal meaning

### ISSUE THREAD

**Issue by ThomasBietenhader** [qualipool/swissrets#21]
The `<start>` element's name does not reveal its purpose. Find a better name, e.g. `availableFrom`.

**Comment by jaggli** [comment]
Good idea. let's rename it to   
`availableFrom`

**Comment by rspuler** [comment]
If I see it correctly you replaced this availableFrom (formerly start) field into the availability tag as start attribute. Right? If so, please correct change log.
```
 <availability start="2012-12-13T12:12:12" expiration="2012-12-13T12:12:13">
    active
</availability>
```
