### ISSUE TITLE
Usage of price, netPrice, grossPrice and extraCost

### ISSUE THREAD

**Issue by ThomasBietenhader** [qualipool/swissrets#22]
There are three prices declared in the schema, namely `price`, `netPrice` and `grossPrice`. Additionally there is an element `extraCost`. The usage of these fields is not explained, but seems to be related to the `propertyType`. The element `price` seems to be used for properties of type `buy` while `netPrice`, `grossPrice` are used for properties of type `rent`. Also `extraCost` seems rather suited for rental properties.

Is this assumption correct? Please clarifiy the usage of these elements.

**Comment by jaggli** [comment]
Related #23
