### ISSUE TITLE
Wärmeerzeugung, Wärmeverteilung vorschlag

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#26]
Wäremeerzeugung (heatGeneration)
===============

* Elektroheizung electric
* Erdsonde geothermal-probe
* Fernwärme district
* Gasheizung gas
* Holzheizung wood
* Luft-Wasser-Wärmepumpe air-water-heatpump
* Ölheizung oil 
* Pelletheizung pellet
* Wärmepumpe heatpump

Wämeverteilung (heatDistribution)
==============

* Bodenheizung floor
* Radiatoren radiators

```
<property>
     <heatGeneration>electric</heatGeneration>
     <heatDistribution>floor</heatDistribution>
</property>
```

**Comment by jaggli** [comment]
Related to #64

**Comment by jaggli** [comment]
solved in #64
