### ISSUE TITLE
Add mobile phone  number to seller.organization

### ISSUE THREAD

**Issue by rspuler** [qualipool/swissrets#27]
We should have the possibility to add two phone numbers to the seller organization (mobile and fixed line).

    ....
    <xs:element type="xs:string" name="phone" minOccurs="0" maxOccurs="1"></xs:element>
    <xs:element type="xs:string" name="mobile" minOccurs="0" maxOccurs="1"></xs:element>
    ....

**Comment by jaggli** [comment]
Or should we allow multiple phone instances instead? Needs clarification.

also related to #68

**Comment by jaggli** [comment]
done in `feature/refactoring`
