### ISSUE TITLE
e-Parkplätze & Solaranlage & Photovoltaik

### ISSUE THREAD

**Issue by qualipool** [qualipool/swissrets#29]
Von: Mario Haller (in Bezug auf IDX)
Neue Felder Vorschlag:
a.       e-Parkplätze
b.       Solaranlage
c.       Photovoltaik

**Comment by jaggli** [comment]
Let's add
```
property
  > characteristics
    > hasPhotovoltaics
    > hasThermalSolarCollector
    > hasChargingStation
```

And add documentation for everyone of them.
