### ISSUE TITLE
Single Category rejected

### ISSUE THREAD

**Issue by JeromeSamyn-NH** [qualipool/swissrets#37]
We had a listing which was imported with the following informations:

`<categories>
<category>house<category>
</categories>
<utilities>
<utility>residential</utility>
</utilities>
`

The listing was rejected because we couldn't assign a second category (Unterobjektart) to this object.
How should we handle such cases? Is only one category enough? (Hauptobjektart)

**Comment by jaggli** [comment]
I also think we need more than one category, lets discuss that

**Comment by jensstalder** [comment]
I currently don't see why a property should be rejected when the category specified is not "specific" enough. It's true that "house" is a overly general category. But i guess it's in the interest of the publisher to decide what to ultimately accept as a usable listing. But this would be easily fixable by the "listee" if only he was informed that is listing is not "specific" enough to be listed.

**Comment by jaggli** [comment]
@jensstalder hd a look into our data, totally true, we can't force it, this would en up in a guesswork-disaster - until we have AI to solve it for us ;)

**Comment by jaggli** [comment]
Single categories are fine.
