### ISSUE TITLE
Projekt-Publishing

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#4]
Ähnlich wie bei den `<properties>` sollen auch `<projects>` mit Veröffentlichungs-Informationen versehen werden können.

**Comment by jaggli** [comment]
@jensstalder Please specify, what information you mean. The start date? That start date will be renamed into `availableFrom` after we've done #21?

**Comment by jensstalder** [comment]
I meant the original `publishers->publisher` tag, to accommodate aggregate distribution systems such as CASAGATEWAY from discerning where projects need to be published to, or to communicate specific infos to the publishers concerning the project. In general `<projects>` is still very rudimentary and is realistically only used by websites at the moment. It's a future concern however.

**Comment by jaggli** [comment]
Ok so I won't t set the 1.0.0 milestone for this.

**Comment by jaggli** [comment]
Closed, until we have a usecase for this, then we'll reopen it.
