### ISSUE TITLE
Is it intended / desirable to exchange information which is not (yet) standardised?

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#43]
## Main topic

- [x] Technical understanding
- [ ] Missing documentation
- [x] Contributing and community
- [ ] other: __________

## Precise and short description of your question
As real estates portal we are interested in having as many pieces of information about the objects as possible. We understand that the list of supported features in swissRETS must be finite, but we will probably run into the situation that e.g. casasoft has information which we're interested in, but wich cannot be standardised for whatever reason. Can you explain how we can achieve dynamic data exchange without having to release new versions every few weeks?

**Comment by jaggli** [comment]
solved in #65
