### ISSUE TITLE
How to identify the primary language for multiple offer elements?

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#44]
## Main topic

- [x] Technical understanding
- [x] Missing documentation
- [ ] Contributing and community
- [ ] other: __________

## Precise and short description of your question
There is an element called offers of type list, where the language is an attribute: 
``
<offers>
                <offer id="offer123de" lang="de">
``
If there are multiple offer elements with different languages, how do I know which is the primary one? (Please do not say the first one wins, because then the outcome is unpredictable depending on the implementation of the xml parser).

**Comment by jaggli** [comment]
This is defined already in the schema, by ordering the `<offers>` (which will be renamed to `<localizations>`)
