### ISSUE TITLE
Customer text formatting

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#45]
## Main topic

- [x] Technical understanding
- [x] Missing documentation
- [ ] Contributing and community
- [ ] other: __________

## Precise and short description of your question
Today, we allow the customers to format their descriptions with a limited set of html tags. This is error prone and not very reliable. Is it foreseen to offer custom formatting in swissRETS? If yes, which formatting language should be supported, and how do we know which elements allow such formatting?

**Comment by jaggli** [comment]
We definitely need this and we should not use HTML for this. HTML would already suggest the use case of the standard - which is bad by definition. 
Think about
- Mobile Apps
- Desktop Software
- Security (embedding tags somewhere is and will always be tricky) 
- Other thing, that use the standard, without being in touch with HTML

## Suggestion
We should use Markdown for this and disallow markup and also links in markdown
Let's define a minimal set of Markdown features to enable
- Bold
- Unordered-Lists
- ...do we need more?

(not sure if we need italic, probably not)

### How we know which elements allow such formating
- defined in the XSD
- maybe like this `<description content-type="markdown">`

**Comment by jaggli** [comment]
We will
- do nothing
