### ISSUE TITLE
Missing object categories compared to IDX 3.01

### ISSUE THREAD

**Issue by herrmannsimon** [qualipool/swissrets#46]
## Precise and short description of your question
Why were categories which are part of IDX omitted in SwissRETS?
There are about 31 object categories from IDX missing in SwissRETS, of which many (e.g. Atelier, Industrial object, Restaurant & others) are important and demanded

**Comment by jaggli** [comment]
We will
- create a list of all those things
- add the values of Homegate and ImmoScout24
- decide which we should add
- remove the limitation of 3 categories

**Comment by jaggli** [comment]
https://docs.google.com/spreadsheets/d/1NKx8oDF16AMF8nMXmaa4OQTC0iu9NdDPB2rN1pCa2vA/edit#gid=0 @herrmannsimon @adi-de-masi can you please fill in your values

**Comment by jaggli** [comment]
Data showed, we should probably keep these:
- appartement
- duplex
- attic-flat
- roof-flat
- studio
- single-room
- furnished-flat
- terrace-flat
- loft
- single-house
- row-house
- bifamiliar-house
- terrace-house
- villa
- farm
- multiple-dwelling
- chalet
- rustico
- office
- retail-space
- hobby-room

Let's go with those, we still can add more, if we need to

**Comment by jaggli** [comment]
Also added all documentation into wiki.
