### ISSUE TITLE
Unique senderId

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#47]
**Is your feature request related to a problem? Please describe.**
When analysing issues with formally wrong requests, it is sometimes hard to say whether the issue is caused by a software problem or if a user managed to do it wrong. A unique senderId would help finding general problems caused by the originating software. In addition to bugtracking, it would also help planning migrations or version changes.

**Describe the solution you'd like**
We suggest to make the senderId mandatory, and to introduce a naming pattern that contains the domain name plus the version of the software vendor.

**Additional context**
fictional example: ch.casasoft.v9.22

The format is just a suggestion and can of course be refined/changed, as long as it uniquely identifies the vendor.

**Comment by jaggli** [comment]
https://github.com/qualipool/swissrets/blob/master/schema/schema.xsd#L522

We will
- rename `<exporter>` to `<software>`
- add "version" attribute to `<software>`
- add `<schemaVersion>`
