### ISSUE TITLE
Add translations to documentation

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#48]
**Is your feature request related to a problem? Please describe.**
Many of the features currently described in enums have unclear or ambiguous names. In the corresponding "docs" markdown file, there are additional explanations which might help clarifying what the meaning of those enums is.
Ambiguous names are confusing, different real estates platforms will sooner or later display the same feature differently, and tracking / resolving the issues will waste a lot of resources because also negotiation will be needed ('who did it wrong?').

**Describe the solution you'd like**
Instead of describing the keywords outside of the schema, we suggest two options:

1. Introduce a complex type "feature" to replace the enums in "featureTypes" and "numericValuekeys". That new type should have two additional elements: **type** (numeric, boolean, could even be more explicit like cubic, are, distance..), and **translations** (default translations for de, en, fr, it).
2. Improve the documentation for each enum significantly using the \<annotation\>\<documentation\> tags, get rid of external documentation.

**Additional context**
For suggestion 1: Declare the translations as "default" or "fixed" attributes in the schema, so that they do not become part of the payload.

**Comment by jaggli** [comment]
This is related to #65

**Comment by jaggli** [comment]
We will
- include the english names and a description in english for all the `<characteristics>`, `<attachements>`, `<seller>`... and others, where it makes sense

**Comment by jaggli** [comment]
Documented everything as discussed.
