### ISSUE TITLE
Improve descriptions

### ISSUE THREAD

**Issue by adi-de-masi** [qualipool/swissrets#49]
**Is your feature request related to a problem? Please describe.**
Identifying the exact purpose of a description in the \<descriptions\> is not easy and leaves room for interpretation. There is only an optional "title" element to explain the content in the description element. As real estate platform, it is crucial to know without any doubt what the free texts are meant to be.

**Describe the solution you'd like**
Replace the \<descriptions\> list of texts with a more concise type. Here is a suggestion:
```
<texts>
    <title>Einfacher Vermarktungstitel</title>
    <excerpt>Kurzfassung des Angebots</excerpt>
    <situation>Die lage des Angebots</situation>
    <description><![CDATA[<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque solum ea communia, verum etiam paria esse dixerunt.</p>]]></description>
</texts>
```

**Additional context**
Note that the custom formatting in the \<description\> above is **not** part of this feature request, see https://github.com/qualipool/swissrets/issues/45 for that.

**Comment by jaggli** [comment]
The other day I was thinking if we should group all language specific tags under one parent, something like the following (I did not think it through, I'll just drop it here, for reference)

```xml
<localization lang="de">
    <title>Einfacher Vermarktungstitel</title>
    <excerpt>Kurzfassung des Angebots</excerpt>
    <situation>Die lage des Angebots</situation>
    <description><![CDATA[<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque solum ea communia, verum etiam paria esse dixerunt.</p>]]></description>
</localization>
<localization lang="en">
    <title>Simple title</title>
    <excerpt>Kurzfassung des Angebots</excerpt>
    <situation>Die lage des Angebots</situation>
    <description><![CDATA[<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Neque solum ea communia, verum etiam paria esse dixerunt.</p>]]></description>
</localization>
```

My idea
- Do not allow language specific things outside the localization tag
- This would make things really obvious

**Comment by jaggli** [comment]
done in `feature/refactoring` branch
