### ISSUE TITLE
Anfrage E-Mails sollen mit verarbeitungs-optionen spezifiziert werden können.

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#5]
Damit Portale Erkennen können in welcher art eine Anfrage vom Makler/Software erwartet wird sollte es im Standart möglich sein die Portale darauf aufmerksam zu machen. Aka. Remcat, Html E-Mail, ecat, etc.

**Comment by jensstalder** [comment]
I would keep this feature slated to a future release. This has not been used as of now.
It certainly will need a draft in the future.

**Comment by jaggli** [comment]
Cool. I'll make a new Issue with the idea condensed and close this one
