### ISSUE TITLE
Clarify structure and meaning of seller contacts

### ISSUE THREAD

**Issue by rspuler** [qualipool/swissrets#52]
### Main topic
- [ ] Technical understanding
- [x] Missing documentation
- [x] Contributing and community
- [ ] other: __________

### Precise and short description of your question
The structure of the contacts in the seller section of the schema is partly inconsistent. There are several parts of contact information:

- organization contact info as child of the seller.organization element.
- viewPerson, visitPerson, inquryPerson as direct child of seller element

Example:
```xml
<seller>
  <organization id="">
    <address>
    ....
    </address>
    ....
    <email>info@casasoft.ch</email>
    <emailRem>casasoft@remcat.ch</emailRem>
    <fax>no</fax>
    <phone>+41 71 686 94 94</phone>
  </organization>
  <viewPerson>  
     ....
    <email>max.muster@hotmail.com</email>
    <fax></fax>
    <phone></phone>
    <mobile></mobile>
     ....
  </viewPerson>
  <visitPerson>
     ....
    <email>max.muster@hotmail.com</email>
    <fax></fax>
    <phone></phone>
    <mobile></mobile>
     ....
  </visitPerson>
  <inquiryPerson>
     ....
    <email>max.muster@hotmail.com</email>
    <fax></fax>
    <phone></phone>
    <mobile></mobile>
     ....
  </inquiryPerson>
</seller>
```
Further the semantic difference of visitPerson vs viewPerson is not obvious.

### Proposed change
- Use same XSD type for all contact info. Maybe type **person** could be renamed to contact?
- Group contacts (at least view, visit, inquiry) as child elements under a contact (persons) element.
- Clarify the difference of view and visit person either by using different names or at least documenting what they mean. By looking at the schema it is not clear to us.

Contact section could be structured like this:
```xml
<seller>
  <organization id="...">
  ....
  </organization>
  <contacts>
    <view>
    ...
    </view>
    <visit>
    ...
    </visit>
    <inquiry>
    ...
    </inquiry>
  </contacts>
</seller>
```

**Comment by jaggli** [comment]
awesome idea and proposal

**Comment by jaggli** [comment]
We will:
- documnent the types

We won't
- rename
- encapsulatate

**Comment by jaggli** [comment]
done in `feature/refactoring` branch
