### ISSUE TITLE
Group price-related fields

### ISSUE THREAD

**Issue by lucashedinger** [qualipool/swissrets#53]
**Is your feature request related to a problem? Please describe.**
Currently there are about 7 fields related to the cost and pricing of a listing.  Because they are not grouped it makes the XML less readable. The naming also has room for improvement.

**Describe the solution you'd like**
Straightforward approach would be to group all the fields related to price. This contributes to the overall hygiene of the schema. In addition the explicit "price" prefix would also no longer be necessary for each child element, as it is implicit by the parent "price" element. See example below:

**Additional context**
```
<property id="property123">
   ...
    <price>
        <currency>CHF</currency>
        <net>1200</net>
        <gross>1450</gross>
        <mandatoryCosts> <!-- previously extraCosts -->
            <mandatoryCost key="k">50</mandatoryCost>
        </mandatoryCosts>
        <optionalCosts> <!-- previously integratedOffers -->
            <optionalCost type="someType" inclusive="0">100</optionalCost>
        </optionalCosts>
    </price>
   ...
</property>
```

**Comment by jaggli** [comment]
I like the idea, let's try to make it even more straight forward

```
<property id="property123">
   ...
    <prices currency="CHF" frequency="1" frequencyUnit="month" referring="m2">
        <net>1200</net>
        <gross>1450</gross>
        <mandatoryCosts>
            <mandatoryCost key="k">50</mandatoryCost>
        </mandatoryCosts>
        <optionalCosts>
            <optionalCost type="someType" isIncluded="0">100</optionalCost>
        </optionalCosts>
    </price>
   ...
</property>
```

**Comment by lucashedinger** [comment]
Excellent!
The same idea actually went through my head as well, so I'm glad you're suggesting it.

**Comment by jaggli** [comment]
comming in 1.0.0
