### ISSUE TITLE
is_minergie_certified --> Feld (Minergie-Standard Zertifikatsnummer)

### ISSUE THREAD

**Issue by sunilkale74** [qualipool/swissrets#58]
is-minergie-certified --> Feld (Minergie-Standard Zertifikatsnummer)

**Comment by jaggli** [comment]
this is mentioned in #65 -> clarify it first

**Comment by jaggli** [comment]
```xml
<minergieCertification></minergieCertification>
```
- Minergie
- Minergie-P
- Minergie-Eco
- Minergie-P-Eco

**Comment by jaggli** [comment]
done in `feature/refactoring` branch

**Comment by jaggli** [comment]
Accodring to the Skype of 06.12. we want to move this field out of characteristics. One level up directly into property

**Comment by jaggli** [comment]
moved it out of characteristics in `feature/refactoring`
