### ISSUE TITLE
categories / utilities

### ISSUE THREAD

**Issue by sunilkale74** [qualipool/swissrets#6]
Hi Jens,

Eine Frage zu der Nutzung/Kategorisierung (XSD). Haben wir hier (siehe Abschnitt XSD unten) die Möglichkeit vorgesehen mehrere Nutzungsarten (utilities) pro Objekt sowie mehrere Kategorien (categories) zuzulassen und wie kommt ihr auf maximal drei (maxOccurs=3)?

Danke und Gruss,
Sunil

                    <xs:element name="categories" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="categoryTypes" name="category" minOccurs="1" maxOccurs="3"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="utilities" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="utilityTypes" name="utility" minOccurs="1" maxOccurs="3"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

**Comment by jensberndt** [comment]
Hi Sunil,
gute Frage. Habe ich auch auf meiner Liste der offenen Punkte. Wurde vor meiner Zeit bei Homegate besprochen. Am besten die Frage direkt ins Git posten - Basil hat bestimmt erstmal eine Antwort. Ob uns dies dann ausreicht, müssen wir anschliessend sehen.

Viele Grüsse
Jens

**Comment by sunilkale74** [comment]
Ähhm... sorry... wie und wo mach ich das genau (ins Git posten :-)

**Comment by jensstalder** [comment]
There should be no such restriction. Was probably added due to some sort of "fear" during the first draft. Consumers can decide to, for example, only consider the first 3. The order is important however, aka the first one stated is the one the sender wants, if that does'nt work go to 2 then 3 etc. I can't see that restricting this would help.

**Comment by jaggli** [comment]
Thank you. Ok we will:
- keep the sequence
- remove the restriction
