### ISSUE TITLE
number_of_showers

### ISSUE THREAD

**Issue by sunilkale74** [qualipool/swissrets#62]
Anzahl Duschen

**Comment by jaggli** [comment]
clarify #65 first

**Comment by jaggli** [comment]
@merrycoder I think there went something wrong. Can you please fix this, thx

![2018-11-28 at 14 02](https://user-images.githubusercontent.com/152748/49153855-3c85d000-f317-11e8-98f5-b250f3b71f20.png)
![2018-11-28 at 14 02](https://user-images.githubusercontent.com/152748/49153861-3e4f9380-f317-11e8-91ba-0398b295be1d.png)

**Comment by merrycoder** [comment]
fixed @jaggli
