### ISSUE TITLE
heating_system

### ISSUE THREAD

**Issue by sunilkale74** [qualipool/swissrets#64]
generelle Diskussion (Heiz-Systeme)

**Comment by jaggli** [comment]
clarify #65 first

**Comment by jaggli** [comment]
```xml
<heatingSystem>oil</heatingSystem>
```

**Comment by jaggli** [comment]
@sunilkale74 please clarify, what heating systems should be included
@jensstalder you have probably input as well...

**Comment by jensstalder** [comment]
The ones listed on https://github.com/qualipool/swissrets/issues/26 are the ones we use in various software products already, would be great if they are included. #26

**Comment by jaggli** [comment]
I came up with this draft, for consistency. What do you think?
```xml
<property>
  <heating>
    <production>geothermal-probe</production>
    <distribution>floor</distribution>
  </heating>
</property>
```
Production enum:
- district
- electricity
- gas
- geothermal-probe
- heatpump-air-and-water
- heatpump
- wood-pellet
- wood

Distribution enum:
- radiator
- floor

What do you think @sunilkale74 @jensstalder ?

**Comment by jensstalder** [comment]
Usually "production" tends to refer to "construction" and "generation" for something like a "generator" but I could live with that. I think oil might be missing. I also am not a fan of grouping things when not necessary, makes documenting fields and importing just a little more involved. But again I could live with that.

**Comment by jaggli** [comment]
Good point about the misleading meaning of production. Let's stick with "generation" (this might also be a little bit misleading. generation can also mean "development stage", and the reason, why I changed it. but this is probably a lesser evil.

The grouping is to avoid repetition (heatingXY.., heatingYZ.., heatingWhatever..) and to increase the readability.

Just added oil tot he list, thank you. 

Don't worry about documentation, I'll take care about this.

Update:
```xml
<property>
  <heating>
    <production>geothermal-probe</production>
    <distribution>floor</distribution>
  </heating>
</property>
```
Production enum:
- district
- electricity
- gas
- geothermal-probe
- heatpump-air-and-water
- heatpump
- wood-pellet
- wood
- oil

Distribution enum:
- floor
- radiator
