### ISSUE TITLE
Merge features and numericValues into characteristics

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#65]
**Is your feature request related to a problem? Please describe.**
- Because <features> and <numericValues> do the same thing, just with another data-type, we should group them together. 
- To make things obvious, we should choose a good name, like `<characteristics>`
- This also helps to extend the attributes in the future

**Example with naming**
1. join them together as the example shows below
2. clean up all the names, wo we're using the same patterns for the same things (lower case, dash separated)

### new
```xml
<characteristics>
  <!-- booleans -->
  <allowsPets>false</allowsPets>
  <hasParking />
  <hasGarage />
  <hasRestroom>true</hasRestroom>
  <hasWaterSupply />

  <!-- numeric values -->
  <areasSiaNf>190</areasSiaNf>
  <yearBuilt>2000</yearBuilt>
</characteristics>
```

- [ ] TODO: document what true/false/null means @jaggli 

### (we currently have this)
```xml
<features>
  <feature>has-elevator</feature>
  <feature>has-parking</feature>
  <feature>has-garage</feature>
  <feature>is-wheelchair-accessible</feature>
  <feature>has-restrooms</feature>
  <feature>has-water-supply</feature>
</features>
<numericValues>
  <value key="area_sia_nf">190</value>
  <value key="year_built">2000</value>
</numericValues>
```

**Comment by adi-de-masi** [comment]
This is a good imprivement IMO. I suggest to introduce a complex type in order to define what kind of attribute it is (as opposed to @jaggli s suggestion to group them visually with a comment. This would allow a flexible way to extend the attributes without having to change the schema over and over again, see also #42.

**Comment by jaggli** [comment]
done in feature/refactoring branch
