### ISSUE TITLE
Will there be a joint review of these changes mentioned? Seams like alot of changes need to be audited.

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#67]
https://github.com/qualipool/swissrets/releases

A couple of examples:

* onEvenGround and isGroundFloor mean to separate things. One is on what floor it is and the other if the construction/building is on an even surface.
* arePetsAllowed "are" has not ben used as a prefix before, should be considered.
* I remember isAllowedAsSecondaryResidency and isSecondaryResidenceAllowed was on purpose, something legal I think, can't remember what though.

etc.

**Comment by jaggli** [comment]
Yes, definitely we need a review of multiple people. that's why I'm documenting things exactly. These are all just proposals to be as clean as possible.

**Comment by jaggli** [comment]
I will undo the onEvenGround, it makes sense now

**Comment by jaggli** [comment]
everyone should have gotten an invitation for the skype. otherwise please tell me
