### ISSUE TITLE
Expected feedback field

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#69]
**Problem**
It would be handy for portals, to know what kind of feedback the publisher expects.

**Describe the solution you'd like**
`property > expectedFeedback`

with an enum of
- remcat
- ecat
- email-html
- email-text
- swissrets-feeedback

This is a condensed feature request of the discussion in #5

**Comment by jensstalder** [comment]
We should hold on implementing this untill swissrets-feedback at least partialy implemented to also consider non-email feedback possibilities.

**Comment by jensstalder** [comment]
This does not appear to be a per-property setting but instead a company-wide one.

Currently SwissRETS only supports properties themselves and not settings that are company-wide. Publishers are currently configuring companies/providers on their end. Could be interesting in the future.
