### ISSUE TITLE
WIR-Anteil

### ISSUE THREAD

**Issue by basilmartin** [qualipool/swissrets#7]
WIR-Anteil Ja / Nein, Anteil in %

**Comment by jaggli** [comment]
Related to #65

**Comment by jaggli** [comment]
Let's move this to buying price
`property > prices > buy > priceWirPercentage`

type: percentage (already present in global types)
documentation: "Percentage amount of the price, wich is payable using CHW, a currency created by the WIR Bank of Switzerland".
