### ISSUE TITLE
Required SwissRETS version field

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#73]
**Is your feature request related to a problem? Please describe.**
We should safe the SwissRETS version somewhere in the `export` to let the parsers/users know, what they should use to interpret it.

What do you think? What would be the best approach to this?

**Comment by jaggli** [comment]
@jensstalder some suggestions?

**Comment by jensstalder** [comment]
Hmm maibe It would make sence to make this actually functional, by providing a new template link for each new schema version?
aka: adjusting the `<?xml-stylesheet type="text/xsd" href="https://raw.githubusercontent.com/qualipool/swissrets/master/schema/schema.xsd"?>`
?
Tu use the actual branch something like
`<?xml-stylesheet type="text/xsd" href="https://raw.githubusercontent.com/qualipool/swissrets/release/1.0.0/schema/schema.xsd"?>`
By using the actual schema there wont be mixups aka. defining a different version than what it's being validated agains. 
Or maibe even use the releases feature from github aka use the tag?
``
Do you know how to do this efficiantly or maibe even autmatic during new releases?

**Comment by jaggli** [comment]
@jensstalder I guess what you mean is not stylesheet, but schema location https://www.w3.org/TR/xmlschema-1/#schema-loc right?

**Comment by jensstalder** [comment]
Yup the resulting tag used in the prodoction xml is `<stylsheet *` as definded in the "Example" within the link you provided. Or are you planing on changing that in 1.0.0 .

**Comment by jaggli** [comment]
So far I never saw an XSD acting as a stylesheet, is this common? So far I only used XSL as stylesheets...

**Comment by jaggli** [comment]
UPDATE: doesn't seem to be right, only two google search results, and one is from our repo 
https://www.google.com/search?&q=%22xml-stylesheet+type%3Dtext%2Fxsd%22

**Comment by jensstalder** [comment]
Maibe from here? https://www.w3.org/TR/2010/REC-xml-stylesheet-20101028/#introduction can't remember but it was probably auto added through a tool.

**Comment by jensstalder** [comment]
Meh! this seams all way to complicated. Maibe a `<basedOnXsd>` would be much simpler.

**Comment by jaggli** [comment]
I think the correct way to handle it, is to use schema location, like this:

https://stackoverflow.com/a/3966381

**Comment by jaggli** [comment]
added it to the examples, will also add an automated deployment process for the urls, but probably not for the 1.0.0 milestone
