### ISSUE TITLE
Collaborative work space

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#75]
**Feature description**
Currently there is no way to store collaborative work spaces.

**Desired Solution**
A way to describe collaborative work space. Add a characteristic `hasCollaborativeWorkSpace` (corresponding to `hasFlatSharingCommunity`)

**Comment by jensstalder** [comment]
Makes sence to me. We should slate that wor v2.1. If noone intervenes it will be added by then.

**Comment by jensstalder** [comment]
Currently implemented `hasFlatSharingCommunity` might need to be changed (Same with collaborativeWorkspace):

```
   <isSuitableForFlatSharingCommunity />
```
OR
```
  <isAllowedForFlatSharingCommunity />
```
OR we define a category
```
  <categories><category key="flat-sharing-community" /></categories>
```

**Comment by jensstalder** [comment]
Reopen when we have more energy :-)
