### ISSUE TITLE
Space for living at an advanced age

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#76]
**Prolem description**
A lot of customers want to advertise spaces for living at an advanced age, and fail to do so.

**Desired Solution**
A way to describe spaces for living at an advanced age, such as
- Apartments for senior citizens
- Residences for senior citizens
- maybe more

New characteristics? Not sure

**Comment by jensstalder** [comment]
We discussed this. At the moment we could not find use cases.
