### ISSUE TITLE
New more generic / non-SIA / simple / intuitive areas

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#78]
**Problem description**
Some areas need to be made available that are not specific to SIA, and are meant to be informative more simple and intuitive areas.

**Desired Solution**
```
<characteristics>
    <areaCellar>123</areaCellar>
    <areaBalcony>123</areaBalcony>
    <areaTerrace>123</areaTerrace>
    <areaLoggia>123</areaLoggia>
    <areaGarden>123</areaGarden>
</characteristics>
```

**Comment by jaggli** [comment]
How came, the SIA values are in the standard? Should we remove them entirely? I don't see any benefit.

**Comment by jensstalder** [comment]
Sadly not all areas are covered with the Sia spec. Only areas relevant to architecture and construction. More specific areas such as cellar/loggia for example are not aw fahr as I know.
