### ISSUE TITLE
Bathroom with window

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#79]
**Problem description**
For a lot of people, it's important to have a window in their bathroom, to prevent mold for example.

**Desired Solution**
`numberOfBathroomsWithWindow` characteristic. We already have `numberOfBathrooms` we can use them in combination, for example if one bathroom has a window and the other one doesn't.

**Comment by jensstalder** [comment]
Makes sence to me. We should slate that for v2.1. If nobody intervenes it will be added by then.

**Comment by jensstalder** [comment]
Not important enough (for now). :-)
