### ISSUE TITLE
release notes for version 1.0.0 are incomplete and sometimes wrong

### ISSUE THREAD

**Issue by rtack** [qualipool/swissrets#81]
- has-isdn was removed in 1.0.0 but is not mentioned
- the renamed section says hasTumbler is now hasDryer, however it is called hasTumbleDryer in 1.0.0

release notes should be corrected.

**Comment by rtack** [comment]
in case they are updated, there is also a typo: obsoltete --> obsolete

**Comment by jaggli** [comment]
thank you, -> updated
