### ISSUE TITLE
Land element in prices has type string

### ISSUE THREAD

**Issue by rspuler** [qualipool/swissrets#82]
### Problem description
The land element in the price section has type string. All other prices are of type positiveInteger.
Is there a reason for it? The description suggests that it is always in square meters.
````
<xs:element name="land" type="xs:string" minOccurs="0" maxOccurs="1">
  <xs:annotation>
    <xs:documentation>Land price per m²</xs:documentation>
  </xs:annotation>
</xs:element>
````
### Desired Solution
The element land should also have type `xs:positiveInteger`

**Comment by jensstalder** [comment]
Does seam like a mistake, but I can weekly remember that there was a reason?

**Comment by jensstalder** [comment]
propertyLandPrice was moved to here as "land" from the old spec.

The original propertyLandPrice was never used. We will remove it for now in 2.0
