### ISSUE TITLE
Prices - on request

### ISSUE THREAD

**Issue by rspuler** [qualipool/swissrets#84]
## Main topic

- Technical understanding
- Missing documentation

## Precise and short description of your question

How can we handle the case if the seller does not want to provide a price but the price is on request? Gross price is mandatory for rent, price is mandatory for buy.

**Comment by jensstalder** [comment]
The Tag itself should be optional. Ommiting the tag would imply "on Request". This is how this was handled historically (IDX, CasaXML) and seams to still make sense today. But you are right, this should be better Documented.

**Comment by jaggli** [comment]
Children of <prices> are all optional
