### ISSUE TITLE
There seems to bee minOccures="1" defined by logos and images. There is no way to send a property without logos/images.

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#85]
**Describe the bug**
There seems to bee minOccures="1" defined by logos and images. There is no way to send a property without logos/images.

**To Reproduce**
Try to validate a schema without a defined logo.

**Expected behavior**
minOcures="0"

**Videos / screenshots**
![Screenshot 2019-04-05 at 12 50 08](https://user-images.githubusercontent.com/4964495/55622880-b9cbc080-57a1-11e9-92ef-61b8ac54d891.png)

**Additional context**

**Comment by jaggli** [comment]
in #90
