### ISSUE TITLE
Parking: How to communicate type of parking in the absence of suitable categories?

### ISSUE THREAD

**Issue by ThomasBietenhader** [qualipool/swissrets#86]
## Categories for Parking

- [x] Technical understanding
- [x] Missing documentation
- [ ] Contributing and community
- [ ] other: __________

## How to communicate type of parking
The categories for the utilization "Parking" have been removed. How can the type of parking be communicated? I've used the according values in the characteristics element. But this does not feel right.

**Comment by jaggli** [comment]
@ThomasBietenhader this will be able with the next release, please refer to this list, on how we agreed, IDX 3.01 mapping should work.
https://docs.google.com/spreadsheets/d/1NKx8oDF16AMF8nMXmaa4OQTC0iu9NdDPB2rN1pCa2vA/edit#gid=1387607905
