### ISSUE TITLE
Number of Guest Toilets

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#9]
This numeric value is missing.

**Comment by jensstalder** [comment]
OpenImmo:
```
immobilie->flaechen->anzahl_sep_wc
```

Suggestions for termSlug:

```
number_of_additional_toilets
number_of_seperate_toilets
```

**Comment by jaggli** [comment]
related to #65

**Comment by jaggli** [comment]
Let's have 
`property > characteristics > toiletsGuest`

**Comment by jensstalder** [comment]
The old way had some assumptions that might still make sence to consider.
area* prefix for m m2
numberOf* for int values
volume* for m3
etc. etc.

**Comment by jaggli** [comment]
so the idea was to have the plural form for numbers. But I agree, this can be mistaken as a collection or sequence. So I will try it, an report back if I had any issues. I think this could work (also we have everything grouped together, which is a good thing, i think.

**Comment by jensstalder** [comment]
I'm happy with that. (obviously). ;-b
