### ISSUE TITLE
heating costs included

### ISSUE THREAD

**Issue by ffmarcovreydal** [qualipool/swissrets#95]
## Main topic

- Technical understanding

## Precise and short description of question

Where do I put heating-costs?

**Comment by jensstalder** [comment]
At the moment (at least in the swiss market) there is only a "extra-cost" requirement and are not specified that specifically. Is this something you intend to distribute?

**Comment by jaggli** [comment]
Yes, i would also say, include it in the extra-cost. Is there a specific reason, why you think this should be separate?

**Comment by ffmarcovreydal** [comment]
In Germany it is common to separate between extra-costs (water, garbage collection, common electricity) and heating-costs.
On portals you can chose between separating them or have a boolean field to define whether extra-costs include heating costs or not.

I do not know the swiss market that well -> if its not common there I can just add up the two values.

**Comment by jaggli** [comment]
For now, we do not separate the heating costs.
