### ISSUE TITLE
Commission

### ISSUE THREAD

**Issue by ffmarcovreydal** [qualipool/swissrets#96]
## Main topic

- Technical understanding

 Where to I specify the commision?

**Comment by jensstalder** [comment]
Could you clarify? Don't quite get what you mean.

**Comment by ffmarcovreydal** [comment]
The amount of money the real-estate-agent gets (like 3,5% of purchase price) or 10.000 CHE absolutely.
And a separation for the comission of the buyer and the owner.

**Comment by jensstalder** [comment]
We discussed this, and this is not relevant to portals and other marketplaces. Please reopen if you have examples concearning marketplaces. You could always communicate these specific fields using the `<options />` fields.
