### ISSUE TITLE
New heat generation Types

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#97]
**Problem description**
New Energy heat generation types. Solar Thermal and Photovoltaics

**Desired Solution**
New types: `solar-thermal` and `photovoltaics`

**Some translations**

| key | DE | EN |
|--|--|--|
| solar-thermal | Solarthermie | Solar Thermal |
| photovoltaik | Photovoltaik | Photovoltaics |

**Comment by jaggli** [comment]
These got forgotten, I remember us discussing this last November. Let's include it it in v2.0.0
