### ISSUE TITLE
New categories Geschäftshaus & Gewerbeliegenschaft

### ISSUE THREAD

**Issue by jensstalder** [qualipool/swissrets#98]
**Problem description**
Multiple customers have requested these new categories. Commercial property, Commercial building.

**Desired Solution**
New Categories

|DE|EN|
|--|--|
|Gewerbeliegenschaft|Commercial property|
|Geschäftshaus|Commercial building|

**Comment by jaggli** [comment]
To use in combination with utilization `commercial` ?

**Comment by jensstalder** [comment]
I'm just the messenger ^^

They certainly only would make sence in within the utility:commercial context, but we received a number of requests for these in the Software and we will probably be adding those regardless. I'l post them here first because we obviously wan't to have as much parallel with the Standard as possible.

**Comment by jensstalder** [comment]
...
