### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by jaggli** [qualipool/swissrets#99]
**Documentation missing**
- [x] Include IDX 3.01 mapping table in docs
- [x] Documentation page titles
- [ ] Complete [HeatingGeneration](https://github.com/qualipool/swissrets/blob/feature/v2-preparation-work/docs/HeatingGeneration.md) translations and 2x description missing
- [ ] Complete [Availability](https://github.com/qualipool/swissrets/tree/master/docs/Availability.md) translations
- [ ] Complete [Attachments](https://github.com/qualipool/swissrets/tree/master/docs/Attachments.md) - missing translations
- [ ] Complete [Characteristics](https://github.com/qualipool/swissrets/blob/master/docs/Characteristics.md) missing translations

**Comment by jensstalder** [comment]
We will consider translating more fields to keep things more normalized on the platforms.
